### PR TITLE
Fixed Issue Where Options  And Response Body Would Persist In An Unreasonable Way

### PR DESCRIPTION
**Pull request by KMastroluca**
## Issue 
When navigating back to the method screen from the request screen we didn't clear the options vector. I think it's reasonable for the opts vector to persist from the request page down to the view response page but not back upward, it should be cleared to make room for the user to change their mind and make another choice. Otherwise, you have situations where you go back to the home screen with your previous response body or request options stuck on the  bottom of the page.

## Solution
This is how I fix this in app.rs

I add a previous_screen field to App with type Option<Screen> which allows us to init with previous_screen == None which seems logically correct to me.

```rust
pub struct App<'a> {
    /// toml config file
    pub config: Config,
    /// is the app running
    pub running: bool,
    /// cursor position (veritcal)
    pub cursor: usize,
    /// current screen (stack.pop)
    pub current_screen: Screen,
    /// screen stack
    pub screen_stack: Vec<Screen>,
    // Previous Screen 
    pub previous_screen: Option<Screen>,
    /// index of selected item
    pub selected: Option<usize>,
    /// command (curl or wget)
    pub command: Option<Box<dyn CMD>>,
    /// vec of applicable options
    pub opts: Vec<AppOptions>,
    /// Input struct for tui_input dependency
    pub input: Input,
    /// vec for user input to push into
    pub messages: Vec<String>,
    /// input mode (normal or editing)
    pub input_mode: InputMode,
    /// vec of list items to select from
    pub items: Vec<ListItem<'a>>,
    /// list state for tui
    pub state: Option<ListState>,
    /// http response from executed command
    pub response: Option<String>,
    /// database connection
    pub db: Box<DB>,
}
```
 You can see we clearly do init with previous_screen == None here.

```rust
impl<'a> Default for App<'a> {
    fn default() -> Self {


        Self {
            config: Config::default(),
            running: true,
            cursor: 0,
            screen_stack: vec![Screen::Home],
            previous_screen: None,
            selected: None,
            command: None,
            input_mode: InputMode::Normal,
            messages: Vec::new(),
            opts: Vec::new(),
            items: Screen::Home.get_opts(None),
            input: Input::default(),
            state: None,
            current_screen: Screen::Home,
            response: None,
            db: Box::new(DB::new().unwrap()),
        }
    }
}
```

Finally in App::go_to_screen() we take this approach, setting the previous screen,
then matching on screen to see, if we have just navigated to the method screen, 
what was our previous screen? And if it was anything but Home, lets clear the opts vector.
This might not be the best way to do this but it was what made sense to me i guess.

```rust
    pub fn goto_screen(&mut self, screen: Screen) {

        // Record Current Screen As Previous Screen 
        self.previous_screen = Some(self.current_screen.clone());

        // Push New/Next Screen Onto The Screen Stack
        self.screen_stack.push(screen.clone());

        // Set The Current Screen
        self.current_screen = screen.clone();

        self.cursor = 0;
        match screen {
            Screen::Method => {
                // If The Screen We're Going To Is The Method Screen
                // And Our Previous Screen Is Not The Home Screen, Meaning We're Backing Out  
                // Not Moving Forward
            
                if self.previous_screen != Some(Screen::Home) {
                    // Clear Our Options
                    self.remove_all_app_options();
                }   
            }
```

The return to home  button on the response screen calls this remove_all_app_options() function as well, so this should cover our bases for now.

### CODE REVIEW

**Comment by PThorpe92** [comment]
Can you just try to call 
```
app.clear_all_options()
```
each time we get to the method screen, and see if that works first? 

theoretically that should do it but i could be wrong

**Comment by KMastroluca** [comment]
Okay

**Comment by KMastroluca** [comment]
I tried this and this doesnt work as expected either 

```rust
pub fn handle_method_select_screen<B: Backend>(app: &mut App, frame: &mut Frame<'_, B>) {
    app.command = Some(Box::new(Cmd::Curl(Curl::new())));
    handle_screen_defaults(app, frame);

    // Remove All Options
    app.opts.clear();

    if let Some(num) = app.selected {
        app.command
            .as_mut()
            .unwrap()
            .set_method(String::from(METHOD_MENU_OPTIONS[num])); // safe index
        app.goto_screen(Screen::RequestMenu(String::from(METHOD_MENU_OPTIONS[num])));
    }
}
```

**Comment by KMastroluca** [comment]
Yeah no I think have to stick with my guns on this one unless you see a better way to do it.

**Comment by PThorpe92** [comment]
Ok my fault bro, I meant the
```Rust
remove_all_app_options();
```
function, which I had to change to remove 
```Rust
app.goto_screen(Screen::Method);
```
in order for it to work, but I did get this working...

Not trying to be picky here, obviously your fix works just fine, the only reason I'd prefer this fix is to not add another field to the app struct.

https://github.com/PThorpe92/CuTE/compare/main...dev

Can you do something like that ^

**Comment by KMastroluca** [comment]
im actually confused now / youre saying that a call to go_to_page is within remove_all_app_options () and that was causing that function to break navigation?

**Comment by KMastroluca** [comment]
I just dusted the stack by adding a header Content-Type:application/json and -v verbose option and then trying to backout with escape.

overflow

**Review by KMastroluca — COMMENTED** [review]
This should be it, this works fine and doesnt add a new field to App

**Review by PThorpe92 — APPROVED** [review]

**Pull request merged**
